// Generated by CoffeeScript 1.12.7
(function() {
  var key, ref, val;

  ref = require('./src/aurora');
  for (key in ref) {
    val = ref[key];
    exports[key] = val;
  }

  require('./src/devices/node-speaker');

}).call(this);
